security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        user_db:
            id: App\Model\Services\UserRepository
    firewalls:
            # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            access_denied_handler: accessdeniedhandler
        main:
            provider: user_db
            switch_user: true
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
            access_denied_handler: accessdeniedhandler


    password_hashers:
        App\Model\User:
            id: ssha_encoder

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/feedback/send, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/events/attend, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_admin]
        ROLE_admin: [ROLE_buvo, ROLE_ALLOWED_TO_SWITCH]
        ROLE_buvo: [ROLE_stavo,
                    ROLE_EDIT_ALL_USERS,
                    ROLE_REMOVE_ALL_USERS,
                    ROLE_REMOVE_ALL_MAILALIAS,
                    ROLE_EDIT_ALL_MAILALIAS,
                    ROLE_ALLOWED_TO_SWITCH,
                    ROLE_CHANGEPASSWORD_ALL_USERS]
        ROLE_stavo: [ROLE_groupleader]
        ROLE_groupleader: [ROLE_elder]
        ROLE_elder: [ROLE_nordlicht, ROLE_wiki, ROLE_SHOW_ALL_USERS, ROLE_VIEW_ALL_MAILALIAS]

        ROLE_EDIT_ALL_USERS:
        ROLE_REMOVE_ALL_USERS:
        ROLE_SHOW_ALL_USERS:
        ROLE_REMOVE_ALL_MAILALIAS:
        ROLE_VIEW_ALL_MAILALIAS:
        ROLE_EDIT_ALL_MAILALIAS:
        ROLE_CHANGEPASSWORD_ALL_USERS: