engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true
    checks:
      Squiz ControlStructures ControlSignature SpaceAfterCloseParenthesis:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
      - php:
ratings:
  paths:
  - src/**
  - app/**
  - web/**

exclude_paths:
- "tests/"
- "spec/"
- "**/vendor/"
- "var/"
- "bin/"
- "web/css/feedback.css"
- "web/js/feedback.js"
- "web/js/html2canvas.js"
- "web/config.php"
