# docker-compose.yml
version: '3.3'
services:
  php:
    image: pbnl/scotoobo-php:dev
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile

  nginx:
    image: pbnl/scotoobo-nginx:dev
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
    - "7080:80"
