# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user-provider:
            id: data.userRepository

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            access_denied_handler: accessdeniedhandler
        main:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path:   /logout
                target: /
            access_denied_handler: accessdeniedhandler
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/feedback/send, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
    encoders:
        AppBundle\Model\User:
            id: ssha_encoder

    role_hierarchy:
        ROLE_ADMIN: [ROLE_buvo]
        ROLE_buvo: [ROLE_stavo, ROLE_EDIT_ALL_USERS, ROLE_REMOVE_ALL_USERS]
        ROLE_stavo: [ROLE_groupleader]
        ROLE_groupleader: [ROLE_elder]
        ROLE_elder: [ROLE_nordlicht, ROLE_wiki]

        ROLE_EDIT_ALL_USERS:
        ROLE_REMOVE_ALL_USERS:
