version: 2
jobs:
    test:
        machine:
            image: ubuntu-2004:current
        resource_class: medium

        environment:
            TZ: "/usr/share/zoneinfo/America/Los_Angeles"
            DEBIAN_FRONTEND: "noninteractive"
        steps:
            - run: sudo add-apt-repository -y ppa:ondrej/php
            - run: sudo apt-get update
            - run: sudo apt-get -y install git unzip zlib1g-dev sudo php8.1 php8.1-mbstring php8.1-zip php8.1-xml php8.1-xdebug php8.1-curl php8.1-sqlite php8.1-ldap
            - run: sudo sudo update-alternatives --set php /usr/bin/php8.1
            - checkout
            - run:
                name: Install LDAP
                command: |
                    sudo DEBIAN_FRONTEND=noninteractive apt-get -yq --no-install-suggests --no-install-recommends install ldap-utils slapd ; \
                    sudo service slapd stop ; \
                    sudo rm /etc/ldap/slapd.d/* -R ; \
                    sudo slapadd -n 0 -F /etc/ldap/slapd.d -l ./developerEnv/ldap-test-database/ldif/ldap-test-ubuntudatabase-config.ldif ; \
                    sudo slapadd -n 1 -l ./developerEnv/ldap-test-database/ldif/ldap-test-database-data.ldif ; \
                    sudo chown openldap:openldap /etc/ldap/slapd.d/ -R ; \
                    sudo chown openldap:openldap /var/lib/ldap/ -R ; \
                    sudo service slapd start
            - run: rm var/data/data.sqlite -f
            - run: mkdir var/data/ -p
            - run: cp developerEnv/mysql-test-database/data.sqlite var/data/data.sqlite
            - run: sudo phpenmod -v 8.1 pdo_sqlite
            - run: sudo phpenmod -v 8.1 xml
            - run: sudo phpenmod -v 8.1 mbstring
            - run: sudo phpenmod -v 8.1 curl
            - run: sudo phpenmod -v 8.1 ldap
            - run: curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
            - run: php /usr/local/bin/composer install --no-interaction --dev
            - run: ./vendor/bin/phpunit
    build:
        docker:
        - image: circleci/buildpack-deps
        steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.6
        - run:
            name: Login to docker
            command: |
              docker login -u $DOCKER_USER -p $DOCKER_PASS
        - run:
              name: Build application Docker image
              command: |
                  docker-compose build --no-cache
        - run:
              name: Push docker images
              command: |
                docker push pbnl/scotoobo-php:dev
                docker push pbnl/scotoobo-nginx:dev
workflows:
    version: 2
    test_and_build:
        jobs:
        - test
        - build:
              filters:
                branches:
                  only:
                  - master
