version: 2
jobs:
    build:
        docker:
            - image: buildpack-deps:xenial
        environment:
            TZ: "/usr/share/zoneinfo/America/Los_Angeles"
            DEBIAN_FRONTEND: "noninteractive"
        working_directory: /var/www/html
        steps:
            - run: apt-get update && apt-get -y install git unzip zlib1g-dev sudo php php7.0-mbstring php7.0-zip php7.0-xml php-xdebug php7.0-curl
            - checkout
            - run:
                name: Install LDAP
                command: |
                    sudo DEBIAN_FRONTEND=noninteractive apt-get -yq --no-install-suggests --no-install-recommends --force-yes install ldap-utils slapd php7.0-ldap ; \
                    sudo service slapd stop ; \
                    sudo service slapd start
            - run: php composer.phar install --no-interaction --dev
            - run: ./vendor/bin/phpunit